language: node_js  #设置语言

node_js: stable  #设置相应的版本

# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - git config --global user.name "{GH_Name}" # 设置全局用户名
    - git config --global user.email "{GH_EMAIL}" # 设置全局邮箱
    - npm install -g hexo-cli
    - npm install -g gulp
install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g && gulp #生成

after_script:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI 自动生成 于 `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${GH_Token}@${GH_REF}" master:${GH_fz}

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/HiMrHu/H.git  #设置GH_REF