# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    - name: set environment
      env:
        HEXO_DEPLOY_KEY:${{secrets.hexo_deploy_key}}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "HiMrHu"
        git config --global user.email "454053152@qq.com"
    - name: install dependencies
      run: npm install
    
    - name: build hexo
      run: npm run build
    
    - name: push to github
      run: |
        cd ./public
        git init
        git add --all .
        git commit -m "自动生成 于 `date +"%Y-%m-%d %H:%M"`"
        git push --force --quiet master:gh-pages
